# Generated by Django 5.1.3 on 2024-11-21 16:17

import apps.utilts
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название категории')),
                ('image', models.ImageField(upload_to=apps.utilts.upload_to_common, verbose_name='изображение категории')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='название подкатегории')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utilts.upload_to_common, verbose_name='изображение подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='items.category')),
            ],
            options={
                'verbose_name': 'Подкатегории',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='название продукта')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utilts.upload_to_common, verbose_name='изображение продукта')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество товара')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='items.subcategory')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
