# Generated by Django 5.1.3 on 2024-11-19 11:00

import apps.utilts
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название категории')),
                ('image', models.ImageField(upload_to=apps.utilts.upload_to_common, verbose_name='изображение категории')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название продукта')),
                ('image', models.ImageField(upload_to=apps.utilts.upload_to_common, verbose_name='изображение продукта')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название подкатегории')),
                ('image', models.ImageField(upload_to=apps.utilts.upload_to_common, verbose_name='изображение подкатегории')),
            ],
            options={
                'verbose_name': 'Подкатегории',
                'verbose_name_plural': 'подкатегории',
            },
        ),
    ]
