# Generated by Django 5.1.3 on 2024-11-17 12:16

import apps.utilts
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название страницы')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страница',
            },
        ),
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utilts.upload_to_common, verbose_name='картинка')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='текст')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='текст страницы')),
                ('page_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='core.pagename')),
            ],
            options={
                'verbose_name': 'Информационная Страница',
                'verbose_name_plural': 'Информационная Страница',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название статьи')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание статьи')),
                ('link', models.CharField(blank=True, null=True, verbose_name='ссылка на статью')),
                ('page_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='core.pagename')),
            ],
            options={
                'verbose_name': 'Информационная Страница',
                'verbose_name_plural': 'Информационная Страница',
            },
        ),
    ]
